"""create initial tables

Revision ID: adf8e8e0a7c1
Revises: 
Create Date: 2025-04-26 13:07:55.443185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf8e8e0a7c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(255), nullable=True),
    sa.Column('type', sa.String(255), nullable=True),
    sa.Column('state', sa.String(255), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_configurations_id'), 'configurations', ['id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.String(255), nullable=False),
    sa.Column('token', sa.String(255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(255), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),
    sa.Column('email', sa.String(255), nullable=True),
    sa.Column('rol', sa.String(255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(255), nullable=True),
    sa.Column('remember_token', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('causacioncontable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.Integer(), nullable=True),
    sa.Column('id_comprobante', sa.Integer(), nullable=False),
    sa.Column('id_nit', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('fecha_manual', sa.DateTime(), nullable=False),
    sa.Column('id_cuenta', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('tipo', sa.SmallInteger(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('documento_referencia', sa.String(255), nullable=True),
    sa.Column('token', sa.String(255), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_causacioncontable_id'), 'causacioncontable', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_causacioncontable_id'), table_name='causacioncontable')
    op.drop_table('causacioncontable')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_configurations_id'), table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
